### ISSUE TITLE
typo in requirements.txt

### ISSUE THREAD

**Issue by jellonek** [pixers/kostka#1]
As catched by `asdf` under #python.pl @ freenode irc network - you have a typo in requirements.txt 
https://github.com/pixers/kostka/blob/aa4f5bd9a9ce7a90d2e6c6c9b6d938a0a72dbe38/kostka/container.py#L1 imports https://pypi.python.org/pypi/toposort/1.1 but `requirements.txt` has `topsort` in https://github.com/pixers/kostka/blob/aa4f5bd9a9ce7a90d2e6c6c9b6d938a0a72dbe38/requirements.txt#L3 line.

**Comment by Mewp** [comment]
Thanks for the report. It will be fixed in the next update -- that is, most likely at the end of the week.
